Revert "merge the parent branch into the current one, resolve conflicts"
This reverts commit 48dde7dda622428f40f83941acb91bced50f0473, reversing
changes made to 2038d99594acb1171793fcb83e5b1dca6ebcd163.

diff --git a/bamboo-specs/auto-publish.yaml b/bamboo-specs/auto-publish.yaml
--- a/bamboo-specs/auto-publish.yaml
+++ b/bamboo-specs/auto-publish.yaml
@@ -13,10 +13,9 @@ environments:
 
 AutoDeployAndPublish Release:
   # run auto-deploy only after successful build
-  # FIXME: Uncomment in AG-44839
-  # triggers:
-  #   - build-success:
-  #       branch: stable-v5.2
+  triggers:
+    - build-success:
+        branch: stable-v5.1
   tasks:
     - clean
     - checkout:
@@ -43,26 +42,7 @@ AutoDeployAndPublish Release:
             mv chrome-mv3-release.zip chrome-mv3.zip
 
             # Deploying and publishing release in Chrome Web Store.
-            # This script attempts to deploy the browser extension to the webstore with expedited review.
-            # If the expedited review deployment fails (i.e., the exit status is non-zero),
-            # it catches the error and attempts to deploy with a normal review process.
-            # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
-            # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
-            set +e
-            ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish-expedited-review
-
-            # Capture exit code
-            EXIT_CODE=$?
-
-            # Enable errexit as it was set before
-            set -e
-
-            # If expedited review process exited with non-zero status,
-            # try normal review.
-            if [ $EXIT_CODE -ne 0 ]; then
-              echo "Expedited review failed, trying normal review"
-              ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish
-            fi
+            ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish
   requirements:
     - adg-docker: 'true'
   notifications:
@@ -74,11 +54,11 @@ AutoDeployAndPublish Release:
             url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa-extensions-builds
 
 AutoDeployAndPublish Beta:
-  # run auto-deploy only after successful build
-  # FIXME: Uncomment in AG-44839
+  # # TODO: Enable it back when we release 5.1.0
+  # # run auto-deploy only after successful build
   # triggers:
   #   - build-success:
-  #       branch: stable-v5.2
+  #       branch: stable-v5.1
   tasks:
     - clean
     - checkout:
@@ -104,27 +84,28 @@ AutoDeployAndPublish Beta:
             # artifacts inside deploy script.
             mv chrome-mv3-beta.zip chrome-mv3.zip
 
-            # Deploying and publishing beta in Chrome Web Store.
-            # This script attempts to deploy the browser extension to the webstore with expedited review.
-            # If the expedited review deployment fails (i.e., the exit status is non-zero),
-            # it catches the error and attempts to deploy with a normal review process.
-            # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
-            # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
-            set +e
-            ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish-expedited-review
+            # TODO: Enable it back when we release 5.1.0
+            # # Deploying and publishing beta in Chrome Web Store.
+            # # This script attempts to deploy the browser extension to the webstore with expedited review.
+            # # If the expedited review deployment fails (i.e., the exit status is non-zero),
+            # # it catches the error and attempts to deploy with a normal review process.
+            # # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
+            # # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
+            # set +e
+            # ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish-expedited-review
 
-            # Capture exit code
-            EXIT_CODE=$?
+            # # Capture exit code
+            # EXIT_CODE=$?
 
-            # Enable errexit as it was set before
-            set -e
+            # # Enable errexit as it was set before
+            # set -e
 
-            # If expedited review process exited with non-zero status,
-            # try normal review.
-            if [ $EXIT_CODE -ne 0 ]; then
-              echo "Expedited review failed, trying normal review"
-              ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
-            fi
+            # # If expedited review process exited with non-zero status,
+            # # try normal review.
+            # if [ $EXIT_CODE -ne 0 ]; then
+            #   echo "Expedited review failed, trying normal review"
+            #   ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
+            # fi
   requirements:
     - adg-docker: 'true'
   notifications:
