AG-39777: correct usage set -e flag && use branch-overrides for donothing in master by cron
Squashed commit of the following:

commit 82672b7bfa22570085e5564d3a79c1c6f33f397a
Merge: 5a6e198ce 5c478182a
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Feb 19 13:31:53 2025 +0300

    Merge branch 'master' into fix/AG-39777

commit 5a6e198ceb2acd1790a1dcaf5807a03096264372
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Mon Feb 17 18:14:55 2025 +0300

    fix

commit 9ee93b47de02b32aaf0dbc825247259debfab667
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Mon Feb 17 18:00:44 2025 +0300

    cleanup

commit 8f3b6c48276e470ecdff7eb4abdfc887e6e5a46a
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Mon Feb 17 17:58:00 2025 +0300

    AG-39777: correct usage set -e flag && use branch-overrides for donothing in master by cron

diff --git a/bamboo-specs/auto-publish.yaml b/bamboo-specs/auto-publish.yaml
--- a/bamboo-specs/auto-publish.yaml
+++ b/bamboo-specs/auto-publish.yaml
@@ -97,11 +97,19 @@ AutoDeployAndPublish Beta:
             # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
             set +e
             ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish-expedited-review
-            if [ $? -ne 0 ]; then
+
+            # Capture exit code
+            EXIT_CODE=$?
+
+            # Enable errexit as it was set before
+            set -e
+
+            # If expedited review process exited with non-zero status,
+            # try normal review.
+            if [ $EXIT_CODE -ne 0 ]; then
               echo "Expedited review failed, trying normal review"
               ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
             fi
-            set -e
     - checkout: browser-extension
     - any-task:
         plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
