no AutoDeployAndPublish Beta

diff --git a/bamboo-specs/auto-publish.yaml b/bamboo-specs/auto-publish.yaml
--- a/bamboo-specs/auto-publish.yaml
+++ b/bamboo-specs/auto-publish.yaml
@@ -9,7 +9,7 @@ release-naming:
 
 environments:
   - AutoDeployAndPublish Release
-  - AutoDeployAndPublish Beta
+  # - AutoDeployAndPublish Beta
 
 AutoDeployAndPublish Release:
   # run auto-deploy only after successful build
@@ -53,65 +53,65 @@ AutoDeployAndPublish Release:
             name: Deploy webhook
             url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa-extensions-builds
 
-AutoDeployAndPublish Beta:
-  # # TODO: Enable it back when we release 5.1.0
-  # # run auto-deploy only after successful build
-  # triggers:
-  #   - build-success:
-  #       branch: stable-v5.1
-  tasks:
-    - clean
-    - checkout:
-        repository: bamboo-deploy-publisher
-        path: bamboo-deploy-publisher
-        force-clean-build: true
-    - artifact-download:
-        artifacts:
-          - name: chrome-mv3-beta.zip
-    - script:
-        interpreter: SHELL
-        scripts:
-          - |-
-            set -x
-            set -e
+# AutoDeployAndPublish Beta:
+#   # # TODO: Enable it back when we release 5.1.0
+#   # # run auto-deploy only after successful build
+#   # triggers:
+#   #   - build-success:
+#   #       branch: stable-v5.1
+#   tasks:
+#     - clean
+#     - checkout:
+#         repository: bamboo-deploy-publisher
+#         path: bamboo-deploy-publisher
+#         force-clean-build: true
+#     - artifact-download:
+#         artifacts:
+#           - name: chrome-mv3-beta.zip
+#     - script:
+#         interpreter: SHELL
+#         scripts:
+#           - |-
+#             set -x
+#             set -e
 
-            # Fix mixed logs
-            exec 2>&1
-            ls -la
+#             # Fix mixed logs
+#             exec 2>&1
+#             ls -la
 
-            # Rename beta artifact to the final name, this is needed because
-            # we use one common name 'chrome-mv3.zip' for both beta and release
-            # artifacts inside deploy script.
-            mv chrome-mv3-beta.zip chrome-mv3.zip
+#             # Rename beta artifact to the final name, this is needed because
+#             # we use one common name 'chrome-mv3.zip' for both beta and release
+#             # artifacts inside deploy script.
+#             mv chrome-mv3-beta.zip chrome-mv3.zip
 
-            # TODO: Enable it back when we release 5.1.0
-            # # Deploying and publishing beta in Chrome Web Store.
-            # # This script attempts to deploy the browser extension to the webstore with expedited review.
-            # # If the expedited review deployment fails (i.e., the exit status is non-zero),
-            # # it catches the error and attempts to deploy with a normal review process.
-            # # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
-            # # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
-            # set +e
-            # ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish-expedited-review
+#             # TODO: Enable it back when we release 5.1.0
+#             # # Deploying and publishing beta in Chrome Web Store.
+#             # # This script attempts to deploy the browser extension to the webstore with expedited review.
+#             # # If the expedited review deployment fails (i.e., the exit status is non-zero),
+#             # # it catches the error and attempts to deploy with a normal review process.
+#             # # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
+#             # # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
+#             # set +e
+#             # ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish-expedited-review
 
-            # # Capture exit code
-            # EXIT_CODE=$?
+#             # # Capture exit code
+#             # EXIT_CODE=$?
 
-            # # Enable errexit as it was set before
-            # set -e
+#             # # Enable errexit as it was set before
+#             # set -e
 
-            # # If expedited review process exited with non-zero status,
-            # # try normal review.
-            # if [ $EXIT_CODE -ne 0 ]; then
-            #   echo "Expedited review failed, trying normal review"
-            #   ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
-            # fi
-  requirements:
-    - adg-docker: 'true'
-  notifications:
-    - events:
-        - deployment-started-and-finished
-      recipients:
-        - webhook:
-            name: Deploy webhook
-            url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa-extensions-builds
+#             # # If expedited review process exited with non-zero status,
+#             # # try normal review.
+#             # if [ $EXIT_CODE -ne 0 ]; then
+#             #   echo "Expedited review failed, trying normal review"
+#             #   ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
+#             # fi
+#   requirements:
+#     - adg-docker: 'true'
+#   notifications:
+#     - events:
+#         - deployment-started-and-finished
+#       recipients:
+#         - webhook:
+#             name: Deploy webhook
+#             url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa-extensions-builds
