pause auto-builds until new versions will be reviewed

diff --git a/bamboo-specs/auto-publish.yaml b/bamboo-specs/auto-publish.yaml
--- a/bamboo-specs/auto-publish.yaml
+++ b/bamboo-specs/auto-publish.yaml
@@ -13,9 +13,10 @@ environments:
 
 AutoDeployAndPublish Release:
   # run auto-deploy only after successful build
-  triggers:
-    - build-success:
-        branch: stable-v5.2
+  # FIXME: Paused auto-builds until v5.2.112.96 on the review
+  # triggers:
+  #   - build-success:
+  #       branch: stable-v5.2
   tasks:
     - clean
     - checkout: &checkout
@@ -41,27 +42,31 @@ AutoDeployAndPublish Release:
             # artifacts inside deploy script.
             mv chrome-mv3-release.zip chrome-mv3.zip
 
-            # Deploying and publishing release in Chrome Web Store.
-            # This script attempts to deploy the browser extension to the webstore with expedited review.
-            # If the expedited review deployment fails (i.e., the exit status is non-zero),
-            # it catches the error and attempts to deploy with a normal review process.
-            # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
-            # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
-            set +e
-            ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish-expedited-review
+            # FIXME: Paused auto-builds until v5.2.112.96 on the review
+            echo "Publishing beta is disabled until v5.2.112.96 on the review"
 
-            # Capture exit code
-            EXIT_CODE=$?
+            # FIXME: Paused auto-builds until v5.2.112.96 on the review
+            # # Deploying and publishing release in Chrome Web Store.
+            # # This script attempts to deploy the browser extension to the webstore with expedited review.
+            # # If the expedited review deployment fails (i.e., the exit status is non-zero),
+            # # it catches the error and attempts to deploy with a normal review process.
+            # # The 'set +e' command allows the script to continue running even if the expedited review deployment fails.
+            # # The 'set -e' command ensures that the script will exit immediately if any subsequent command fails.
+            # set +e
+            # ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish-expedited-review
 
-            # Enable errexit as it was set before
-            set -e
+            # # Capture exit code
+            # EXIT_CODE=$?
 
-            # If expedited review process exited with non-zero status,
-            # try normal review.
-            if [ $EXIT_CODE -ne 0 ]; then
-              echo "Expedited review failed, trying normal review"
-              ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish
-            fi
+            # # Enable errexit as it was set before
+            # set -e
+
+            # # If expedited review process exited with non-zero status,
+            # # try normal review.
+            # if [ $EXIT_CODE -ne 0 ]; then
+            #   echo "Expedited review failed, trying normal review"
+            #   ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-release-publish
+            # fi
   requirements: &requirements
     - adg-docker: 'true'
   notifications: &notifications
@@ -74,7 +79,7 @@ AutoDeployAndPublish Release:
 
 AutoDeployAndPublish Beta:
   # run auto-deploy only after successful build
-  # TODO: uncomment after halloween release. AG-47227
+  # FIXME: Paused auto-builds until v5.2.112.96 on the review
   # triggers:
   #   - build-success:
   #       branch: stable-v5.2
@@ -100,10 +105,10 @@ AutoDeployAndPublish Beta:
             # artifacts inside deploy script.
             mv chrome-mv3-beta.zip chrome-mv3.zip
 
-            # TODO: remove after halloween release. AG-47227
-            echo "Publishing beta is disabled until release halloween promo"
-            
-            # TODO: uncomment after halloween release. AG-47227
+            # FIXME: Paused auto-builds until v5.2.112.96 on the review
+            echo "Publishing beta is disabled until v5.2.112.96 on the review"
+
+            # FIXME: Paused auto-builds until v5.2.112.96 on the review
             # # Deploying and publishing beta in Chrome Web Store.
             # # This script attempts to deploy the browser extension to the webstore with expedited review.
             # # If the expedited review deployment fails (i.e., the exit status is non-zero),
@@ -119,11 +124,11 @@ AutoDeployAndPublish Beta:
             # # Enable errexit as it was set before
             # set -e
 
-            # If expedited review process exited with non-zero status,
-            # try normal review.
-            if [ $EXIT_CODE -ne 0 ]; then
-              echo "Expedited review failed, trying normal review"
-              ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
-            fi
+            # # If expedited review process exited with non-zero status,
+            # # try normal review.
+            # if [ $EXIT_CODE -ne 0 ]; then
+            #   echo "Expedited review failed, trying normal review"
+            #   ./bamboo-deploy-publisher/deploy.sh browser-extension-webstore-beta-publish
+            # fi
   requirements: *requirements
   notifications: *notifications
