AG-50264: added docker build to build-beta plan
Squashed commit of the following:

commit 79a76659062bad071e1c134e6132ab8015b7cca9
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:47:29 2026 +0300

    fix

commit 03b9017799328c123e6194b44ae8ec3910938528
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:45:55 2026 +0300

    fixed name

commit e896c5b803eedb3f021d28bbbd5bd78ec2b669db
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:45:11 2026 +0300

    clean up

commit 58a80612979c260dcf9d970bef077c3ee2bd7891
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:16:58 2026 +0300

    standardized shell script options and removed debug code from CI configs

commit 2d039f06e4864e78f21255220a95b516281d083b
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:01:32 2026 +0300

    check fail script

commit c602d2237d74a9b7c90368accf95c76dd1850d5e
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Thu Jan 22 14:00:03 2026 +0300

    fixed caching and layers

commit 3e78a7d37c1302799215f50c1f4570d72918fc2c
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 20:42:03 2026 +0300

    ls -la

commit 2d65bb2b28490cb5129c9b4ba77a7e81dfbdad7f
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 20:41:27 2026 +0300

    returned setup script

commit 74f1baa166b43d2abeab4003cfc024c265d424e0
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 19:16:49 2026 +0300

    Revert "removed tag just for debug"
    
    This reverts commit 487b45d10506c56aca954d44c6b6e890eab5c106.

commit 21d238d0995f16d2e6bbd6b602a55aae923772a8
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 16:03:13 2026 +0300

    added --zip flag to beta build in Dockerfile for bundle size check

commit 487b45d10506c56aca954d44c6b6e890eab5c106
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 15:40:03 2026 +0300

    removed tag just for debug

commit 1978fa2483fe00fca9a8f7f830f8595c3fefdb66
Author: Dmitriy Seregin <d.seregin@adguard.com>
Date:   Wed Jan 21 15:36:54 2026 +0300

    AG-50264: added docker build to build-beta plan

diff --git a/bamboo-specs/tests.yaml b/bamboo-specs/tests.yaml
--- a/bamboo-specs/tests.yaml
+++ b/bamboo-specs/tests.yaml
@@ -30,8 +30,10 @@ Test dev build:
         interpreter: SHELL
         scripts:
           - |-
-            set -x
-            set -e
+            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
+            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
+            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
+            set -ex
 
             # Fix mixed logs
             exec 2>&1
@@ -44,7 +46,7 @@ Test dev build:
             # Build with named context for tsurlfilter
             # Docker checksums the context content for cache invalidation
             docker build \
-              --file Dockerfile.test \
+              --file Dockerfile \
               --progress plain \
               --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
               --build-context tsurlfilter=../tsurlfilter \
@@ -103,8 +105,10 @@ Build chrome crx artifact:
         interpreter: SHELL
         scripts:
           - |-
-            set -x
-            set -e
+            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
+            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
+            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
+            set -ex
 
             # Fix mixed logs
             exec 2>&1
@@ -117,7 +121,7 @@ Build chrome crx artifact:
             # Build with named context for tsurlfilter
             # Docker checksums the context content for cache invalidation
             docker build \
-              --file Dockerfile.test \
+              --file Dockerfile \
               --progress plain \
               --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
               --build-context tsurlfilter=../tsurlfilter \
@@ -147,8 +151,10 @@ Lint:
         interpreter: SHELL
         scripts:
           - |-
-            set -x
-            set -e
+            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
+            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
+            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
+            set -ex
 
             # Fix mixed logs
             exec 2>&1
@@ -161,7 +167,7 @@ Lint:
             # Build with named context for tsurlfilter
             # Docker checksums the context content for cache invalidation
             docker build \
-              --file Dockerfile.test \
+              --file Dockerfile \
               --progress plain \
               --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
               --build-context tsurlfilter=../tsurlfilter \
@@ -186,8 +192,10 @@ Unit tests:
         interpreter: SHELL
         scripts:
           - |-
-            set -x
-            set -e
+            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
+            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
+            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
+            set -ex
 
             # Fix mixed logs
             exec 2>&1
@@ -200,7 +208,7 @@ Unit tests:
             # Build with named context for tsurlfilter
             # Docker checksums the context content for cache invalidation
             docker build \
-              --file Dockerfile.test \
+              --file Dockerfile \
               --progress plain \
               --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
               --build-context tsurlfilter=../tsurlfilter \
@@ -237,20 +245,18 @@ Integration tests:
         interpreter: SHELL
         scripts:
           - |-
-            set -e
+            # 'set' should be added to the beginning of each script to ensure that it runs with the correct options.
+            #  -e: Exit immediately if any command exits with a non-zero status (i.e., if a command fails).
+            #  -x: Print each command to the terminal as it is executed, which is useful for debugging.
+            set -ex
+
+            # Fix mixed logs
+            exec 2>&1
+
             mkdir -p artifacts
             if [ -f chrome-mv3-dev.zip ]; then
               mv chrome-mv3-dev.zip artifacts/
             fi
-    - script:
-        interpreter: SHELL
-        scripts:
-          - |-
-            set -x
-            set -e
-
-            # Fix mixed logs
-            exec 2>&1
 
             # Clone tsurlfilter to sibling directory (uses SSH from CI environment)
             ./bamboo-specs/scripts/clone-tsurlfilter.sh
@@ -260,7 +266,7 @@ Integration tests:
             # Build with named context for tsurlfilter
             # Docker checksums the context content for cache invalidation
             docker build \
-              --file Dockerfile.test \
+              --file Dockerfile \
               --progress plain \
               --build-arg TEST_RUN_ID=${bamboo.buildNumber} \
               --build-context tsurlfilter=../tsurlfilter \
